### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by joebywan** [JKolios/minecraft-ondemand-terraform#5]
I'm trying to terraform doctorray's setup aswell mainly as a way to learn more about terraform.

Mine won't load the containers though, has an issue when trying to start the task.

I've compared your version and mine and they're basically the same.  Just wondered if yours works still or not?

https://github.com/joebywan/GameServerIaC/tree/main/terraform

**Comment by JKolios** [comment]
It worked during my last test back in Novemeber (2021). I haven't changed anything significant since then, but there might have been a change on AWS's side, or the minecraft image might have changed significantly (since I'm pulling the `latest` tag in my code). I might test it again in the next days, can't promise anything though.

**Comment by joebywan** [comment]
Awesome, that'd be great :)  It's driving me nuts trying to troubleshoot this :D

**Comment by JKolios** [comment]
Tested this today and I can confirm that [the latest main branch commit ](https://github.com/JKolios/minecraft-ondemand-terraform/commit/a9b9dd8fe3d79ed44184b26c6600381297a52b86) works in my AWS account. The server comes up in 1-2minutes from the first DNS query.

**Comment by joebywan** [comment]
Thanks Jason, appreciate it.  I'll have to figure out what I've done
different.
